<?php

declare(strict_types=1);

use App\Modules\Operations\Application\UpdateMigrationIdentity;
use Illuminate\Contracts\Console\Kernel;
use Illuminate\Database\Connection;

require dirname(__DIR__, 2).'/vendor/autoload.php';

$root = dirname(__DIR__, 2);
$app = require $root.'/bootstrap/app.php';
$app->make(Kernel::class)->bootstrap();

/** @var Connection $connection */
$connection = $app->make('db')->connection();
$database = $connection->getDatabaseName();
if ($database === '') {
    fwrite(STDERR, "Database name is unavailable.\n");
    exit(2);
}

$check = in_array('--check', array_slice($argv, 1), true);
$unknown = array_values(array_filter(
    array_slice($argv, 1),
    static fn (string $arg): bool => $arg !== '--check',
));
if ($unknown !== []) {
    fwrite(STDERR, 'Unknown argument(s): '.implode(', ', $unknown)."\n");
    exit(64);
}

$schemaIdentity = UpdateMigrationIdentity::fromDirectory($root.'/database/migrations');

/** @return list<array<string, mixed>> */
function rows(Connection $connection, string $sql, array $bindings = []): array
{
    return array_map(
        static fn (object $row): array => (array) $row,
        $connection->select($sql, $bindings, false),
    );
}

function cell(mixed $value): string
{
    if ($value === null) {
        return '—';
    }
    if (is_bool($value)) {
        return $value ? 'yes' : 'no';
    }

    $text = trim((string) $value);
    if ($text === '') {
        return '—';
    }

    return str_replace(['\\', '|', "\r", "\n"], ['\\\\', '\\|', ' ', ' '], $text);
}

function codeCell(mixed $value): string
{
    $text = cell($value);

    return $text === '—' ? $text : '`'.str_replace('`', '\\`', $text).'`';
}

/** @param array<string, string> $documents */
function persistDocuments(string $root, array $documents, bool $check): int
{
    $stale = [];
    foreach ($documents as $relative => $content) {
        $path = $root.'/'.$relative;
        if ($check) {
            $current = is_file($path) ? file_get_contents($path) : false;
            if (! is_string($current) || ! hash_equals($content, $current)) {
                $stale[] = $relative;
            }

            continue;
        }

        $directory = dirname($path);
        if (! is_dir($directory) && ! mkdir($directory, 0755, true) && ! is_dir($directory)) {
            throw new RuntimeException('Could not create release-reference directory.');
        }
        if (file_put_contents($path, $content, LOCK_EX) !== strlen($content)) {
            throw new RuntimeException('Could not write '.$relative.'.');
        }
    }

    if ($stale !== []) {
        fwrite(STDERR, 'Generated release reference drift: '.implode(', ', $stale)."\n");

        return 1;
    }

    return 0;
}

$tables = rows($connection, <<<'SQL'
SELECT TABLE_NAME, TABLE_COMMENT
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = ? AND TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME
SQL, [$database]);

$columns = rows($connection, <<<'SQL'
SELECT TABLE_NAME, ORDINAL_POSITION, COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE,
       COLUMN_DEFAULT, COLUMN_KEY, EXTRA, COLUMN_COMMENT
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = ?
ORDER BY TABLE_NAME, ORDINAL_POSITION
SQL, [$database]);

$foreignKeys = rows($connection, <<<'SQL'
SELECT k.TABLE_NAME, k.CONSTRAINT_NAME, k.COLUMN_NAME,
       k.REFERENCED_TABLE_NAME, k.REFERENCED_COLUMN_NAME,
       k.ORDINAL_POSITION, r.UPDATE_RULE, r.DELETE_RULE
FROM information_schema.KEY_COLUMN_USAGE k
JOIN information_schema.REFERENTIAL_CONSTRAINTS r
  ON r.CONSTRAINT_SCHEMA = k.CONSTRAINT_SCHEMA
 AND r.CONSTRAINT_NAME = k.CONSTRAINT_NAME
 AND r.TABLE_NAME = k.TABLE_NAME
WHERE k.TABLE_SCHEMA = ? AND k.REFERENCED_TABLE_NAME IS NOT NULL
ORDER BY k.TABLE_NAME, k.CONSTRAINT_NAME, k.ORDINAL_POSITION
SQL, [$database]);

$uniqueIndexes = rows($connection, <<<'SQL'
SELECT TABLE_NAME, INDEX_NAME, COLUMN_NAME, SEQ_IN_INDEX
FROM information_schema.STATISTICS
WHERE TABLE_SCHEMA = ? AND NON_UNIQUE = 0 AND INDEX_NAME <> 'PRIMARY'
ORDER BY TABLE_NAME, INDEX_NAME, SEQ_IN_INDEX
SQL, [$database]);

$columnsByTable = [];
foreach ($columns as $column) {
    $columnsByTable[(string) $column['TABLE_NAME']][] = $column;
}
$foreignKeysByTable = [];
foreach ($foreignKeys as $foreignKey) {
    $foreignKeysByTable[(string) $foreignKey['TABLE_NAME']][] = $foreignKey;
}
$uniqueIndexesByTable = [];
foreach ($uniqueIndexes as $index) {
    $uniqueIndexesByTable[(string) $index['TABLE_NAME']][(string) $index['INDEX_NAME']][] = (string) $index['COLUMN_NAME'];
}

$data = [];
$data[] = '# Generated Version 1 Data Dictionary';
$data[] = '';
$data[] = '<!-- Generated by scripts/docs/generate-release-references.php; do not edit manually. -->';
$data[] = '';
$data[] = 'This is the release-maintenance data dictionary and relationship reference generated from the fully migrated current schema. Foreign-key rows are the reproducible relationship/ERD source; durable ownership and cross-module rules remain authoritative in [`../05-architecture-overview.md`](../05-architecture-overview.md).';
$data[] = '';
$data[] = '- Migration-set SHA-256: `'.$schemaIdentity.'`';
$data[] = '- Base tables: `'.count($tables).'`';
$data[] = '- Generation command: `php scripts/docs/generate-release-references.php` against an isolated current migrated/seeded database.';
$data[] = '- Verification command: `php scripts/docs/generate-release-references.php --check` against an equivalent isolated database.';
$data[] = '';
$data[] = '> Do not point the generator at production. It performs metadata/reference reads only, but release-reference generation belongs on disposable or otherwise explicitly non-production current schema state.';
$data[] = '';

foreach ($tables as $table) {
    $tableName = (string) $table['TABLE_NAME'];
    $data[] = '## `'.$tableName.'`';
    $comment = trim((string) ($table['TABLE_COMMENT'] ?? ''));
    if ($comment !== '') {
        $data[] = '';
        $data[] = $comment;
    }
    $data[] = '';
    $data[] = '| Column | Type | Null | Default | Key | Extra |';
    $data[] = '| --- | --- | --- | --- | --- | --- |';
    foreach ($columnsByTable[$tableName] ?? [] as $column) {
        $data[] = '| '.codeCell($column['COLUMN_NAME'])
            .' | '.codeCell($column['COLUMN_TYPE'])
            .' | '.(($column['IS_NULLABLE'] ?? 'NO') === 'YES' ? 'yes' : 'no')
            .' | '.codeCell($column['COLUMN_DEFAULT'])
            .' | '.cell($column['COLUMN_KEY'])
            .' | '.cell($column['EXTRA'])
            .' |';
    }

    $tableForeignKeys = $foreignKeysByTable[$tableName] ?? [];
    $tableUniqueIndexes = $uniqueIndexesByTable[$tableName] ?? [];
    if ($tableForeignKeys !== [] || $tableUniqueIndexes !== []) {
        $data[] = '';
        $data[] = '**Relationships / unique constraints**';
        $data[] = '';
    }

    $groupedFks = [];
    foreach ($tableForeignKeys as $foreignKey) {
        $name = (string) $foreignKey['CONSTRAINT_NAME'];
        $groupedFks[$name]['local'][] = (string) $foreignKey['COLUMN_NAME'];
        $groupedFks[$name]['remote'][] = (string) $foreignKey['REFERENCED_COLUMN_NAME'];
        $groupedFks[$name]['table'] = (string) $foreignKey['REFERENCED_TABLE_NAME'];
        $groupedFks[$name]['update'] = (string) $foreignKey['UPDATE_RULE'];
        $groupedFks[$name]['delete'] = (string) $foreignKey['DELETE_RULE'];
    }
    foreach ($groupedFks as $name => $foreignKey) {
        $data[] = '- FK `'.$name.'`: `'.implode(', ', $foreignKey['local']).'` → `'.$foreignKey['table'].'('.implode(', ', $foreignKey['remote']).')`; update `'.$foreignKey['update'].'`, delete `'.$foreignKey['delete'].'`.';
    }
    foreach ($tableUniqueIndexes as $name => $indexColumns) {
        $data[] = '- UNIQUE `'.$name.'`: `'.implode(', ', $indexColumns).'`.';
    }
    $data[] = '';
}
$dataDictionary = rtrim(implode("\n", $data))."\n";

$permissions = rows($connection, <<<'SQL'
SELECT id, code, module, risk_level, requires_approval
FROM permissions
ORDER BY module, code
SQL);
$rolePermissions = rows($connection, <<<'SQL'
SELECT p.code AS permission_code, r.code AS role_code
FROM role_permissions rp
JOIN permissions p ON p.id = rp.permission_id
JOIN roles r ON r.id = rp.role_id
WHERE r.is_active = 1
ORDER BY p.code, r.code
SQL);
$rolesByPermission = [];
foreach ($rolePermissions as $rolePermission) {
    $rolesByPermission[(string) $rolePermission['permission_code']][] = (string) $rolePermission['role_code'];
}

$permissionsDoc = [];
$permissionsDoc[] = '# Generated Version 1 Permission Catalog';
$permissionsDoc[] = '';
$permissionsDoc[] = '<!-- Generated by scripts/docs/generate-release-references.php; do not edit manually. -->';
$permissionsDoc[] = '';
$permissionsDoc[] = 'This catalog is generated from the current seeded `permissions`, active `roles`, and `role_permissions` authorities. Runtime authorization still applies administrator assignments, per-administrator allow/deny overrides, execution-time checks, and sensitive-action approval rules; a default role shown here is not proof that a particular administrator is currently authorized.';
$permissionsDoc[] = '';
$permissionsDoc[] = '- Permissions: `'.count($permissions).'`';
$permissionsDoc[] = '- Generation/verification: same commands as the generated data dictionary.';
$permissionsDoc[] = '- Authorization design: [`../05-architecture-overview.md`](../05-architecture-overview.md) and [`../07-security-threat-model.md`](../07-security-threat-model.md).';
$permissionsDoc[] = '';
$permissionsDoc[] = '| Permission | Module | Risk | Sensitive approval | Default active roles |';
$permissionsDoc[] = '| --- | --- | --- | --- | --- |';
foreach ($permissions as $permission) {
    $code = (string) $permission['code'];
    $roles = $rolesByPermission[$code] ?? [];
    $permissionsDoc[] = '| `'.$code.'` | `'.cell($permission['module']).'` | `'.cell($permission['risk_level']).'` | '
        .((bool) $permission['requires_approval'] ? 'yes' : 'no').' | '
        .($roles === [] ? '—' : '`'.implode('`, `', $roles).'`').' |';
}
$permissionCatalog = rtrim(implode("\n", $permissionsDoc))."\n";

exit(persistDocuments($root, [
    'docs/reference/data-dictionary.md' => $dataDictionary,
    'docs/reference/permission-catalog.md' => $permissionCatalog,
], $check));
