<?php

declare(strict_types=1);

return [
    'allowed_module_dependencies' => [
        'Agents' => ['AccessControl'],
        'Catalog' => ['AccessControl', 'Customers', 'Identity', 'Panels'],
        'Customers' => ['AccessControl', 'Identity'],
        'Identity' => ['AccessControl'],
        'Installer' => ['Operations'],
        'Orders' => ['AccessControl', 'Agents'],
        'Panels' => ['AccessControl'],
        'Payments' => ['AccessControl', 'Orders', 'Wallet'],
        'Promotions' => ['AccessControl', 'Wallet'],
        'Provisioning' => ['AccessControl', 'Catalog', 'Orders', 'Panels', 'Payments', 'Telegram', 'Wallet'],
        'Wallet' => ['AccessControl'],
    ],
    'domain_dependency_exceptions' => [
        'app/Modules/Catalog/Domain/CustomPlanPolicyDefinition.php|Customers\\Domain',
        'app/Modules/Catalog/Domain/OfferingOperationPolicy.php|Panels\\Domain',
        'app/Modules/Catalog/Domain/PlanOfferingDefinition.php|Customers\\Domain',
        'app/Modules/Catalog/Domain/PlanOfferingDefinition.php|Panels\\Domain',
        'app/Modules/Catalog/Domain/TrialPolicyDefinition.php|Customers\\Domain',
        'app/Modules/Catalog/Domain/TrialPolicyDefinition.php|Identity\\Domain',
    ],
    'cycle_exceptions' => [],

    // Exact source of truth for every migration-created durable table. Values are either
    // an owning feature module or a reviewed infrastructure classification. Framework
    // tables are Laravel runtime state; Shared is owned by app/Shared; SharedAppendOnly
    // is a cross-cutting sink that may only receive append operations.
    'durable_table_owners' => [
        'administrator_permission_overrides' => 'AccessControl',
        'administrator_role_assignments' => 'AccessControl',
        'administrator_status_histories' => 'AccessControl',
        'administrators' => 'AccessControl',
        'agent_application_histories' => 'Agents',
        'agent_applications' => 'Agents',
        'agent_pricing_profile_versions' => 'Agents',
        'agent_pricing_profiles' => 'Agents',
        'agent_pricing_resolutions' => 'Agents',
        'agent_pricing_rule_versions' => 'Agents',
        'agent_pricing_rules' => 'Agents',
        'agent_profiles' => 'Agents',
        'agent_status_histories' => 'Agents',
        'alerts' => 'Operations',
        'audit_logs' => 'SharedAppendOnly',
        'benefit_code_campaign_versions' => 'Promotions',
        'benefit_code_campaigns' => 'Promotions',
        'benefit_code_disables' => 'Promotions',
        'benefit_code_discount_grants' => 'Promotions',
        'benefit_code_free_service_entitlements' => 'Promotions',
        'benefit_code_issuances' => 'Promotions',
        'benefit_code_redemptions' => 'Promotions',
        'benefit_codes' => 'Promotions',
        'c2c_amount_reservations' => 'Payments',
        'c2c_bank_transaction_events' => 'Payments',
        'c2c_bank_transactions' => 'Payments',
        'c2c_destination_account_events' => 'Payments',
        'c2c_destination_accounts' => 'Payments',
        'c2c_manual_submissions' => 'Payments',
        'c2c_match_reviews' => 'Payments',
        'c2c_provider_cursors' => 'Payments',
        'c2c_reconciliation_findings' => 'Payments',
        'c2c_transaction_matches' => 'Payments',
        'cache' => 'Framework',
        'cache_locks' => 'Framework',
        'custom_plan_calculation_validations' => 'Catalog',
        'custom_plan_calculations' => 'Catalog',
        'custom_plan_policies' => 'Catalog',
        'custom_plan_policy_histories' => 'Catalog',
        'custom_plan_policy_reserved_words' => 'Catalog',
        'custom_plan_policy_separators' => 'Catalog',
        'custom_plan_policy_tags' => 'Catalog',
        'custom_plan_policy_tiers' => 'Catalog',
        'customer_profiles' => 'Customers',
        'customer_status_histories' => 'Customers',
        'customer_tag_assignments' => 'Customers',
        'customer_tags' => 'Customers',
        'customer_tier_histories' => 'Customers',
        'customer_tiers' => 'Customers',
        'failed_jobs' => 'Framework',
        'gift_card_provider_events' => 'Payments',
        'gift_card_reconciliation_findings' => 'Payments',
        'gift_card_redemptions' => 'Payments',
        'gift_card_reviews' => 'Payments',
        'gift_card_submissions' => 'Payments',
        'gift_card_types' => 'Payments',
        'idempotency_keys' => 'Shared',
        'identity_item_histories' => 'Identity',
        'identity_items' => 'Identity',
        'job_batches' => 'Framework',
        'jobs' => 'Framework',
        'ledger_accounts' => 'Wallet',
        'ledger_entries' => 'Wallet',
        'ledger_refundability' => 'Wallet',
        'ledger_transactions' => 'Wallet',
        'nowpayments_payment_authorities' => 'Payments',
        'nowpayments_payment_observations' => 'Payments',
        'nowpayments_reconciliation_findings' => 'Payments',
        'order_items' => 'Orders',
        'order_state_histories' => 'Orders',
        'orders' => 'Orders',
        'otp_challenges' => 'Identity',
        'outbox_messages' => 'Shared',
        'owner_transfer_requests' => 'AccessControl',
        'panel_capacity_reservation_events' => 'Panels',
        'panel_capacity_reservations' => 'Panels',
        'panel_connection_histories' => 'Panels',
        'panel_connections' => 'Panels',
        'panel_mutation_receipts' => 'Panels',
        'panel_protocol_profile_histories' => 'Panels',
        'panel_protocol_profiles' => 'Panels',
        'panel_service_target_histories' => 'Panels',
        'panel_service_targets' => 'Panels',
        'panel_target_capabilities' => 'Panels',
        'panel_target_capacities' => 'Panels',
        'panel_target_capacity_histories' => 'Panels',
        'panel_target_protocol_profiles' => 'Panels',
        'payment_attempts' => 'Payments',
        'payment_intent_state_histories' => 'Payments',
        'payment_intents' => 'Payments',
        'payment_method_eligibility_decision_methods' => 'Payments',
        'payment_method_eligibility_decisions' => 'Payments',
        'payment_method_health_observations' => 'Payments',
        'payment_method_rule_version_tags' => 'Payments',
        'payment_method_rule_versions' => 'Payments',
        'payment_method_versions' => 'Payments',
        'payment_provider_events' => 'Payments',
        'payment_provider_transactions' => 'Payments',
        'permissions' => 'AccessControl',
        'phone_numbers' => 'Identity',
        'phone_verification_events' => 'Identity',
        'phone_verification_evidences' => 'Identity',
        'plan_offering_auto_renew_policies' => 'Provisioning',
        'plan_offering_auto_renew_policy_histories' => 'Provisioning',
        'plan_offering_histories' => 'Catalog',
        'plan_offering_operations' => 'Catalog',
        'plan_offering_packages' => 'Catalog',
        'plan_offering_protocol_profiles' => 'Catalog',
        'plan_offering_required_capabilities' => 'Catalog',
        'plan_offering_route_policies' => 'Catalog',
        'plan_offering_route_policy_histories' => 'Catalog',
        'plan_offering_route_selections' => 'Catalog',
        'plan_offering_routes' => 'Catalog',
        'plan_offering_tags' => 'Catalog',
        'plan_offering_tiers' => 'Catalog',
        'plan_offerings' => 'Catalog',
        'pricing_rule_resolutions' => 'Promotions',
        'pricing_rule_versions' => 'Promotions',
        'pricing_rules' => 'Promotions',
        'processed_telegram_updates' => 'Telegram',
        'product_categories' => 'Catalog',
        'product_category_histories' => 'Catalog',
        'product_histories' => 'Catalog',
        'product_variant_histories' => 'Catalog',
        'product_variants' => 'Catalog',
        'products' => 'Catalog',
        'promotion_usage_redemptions' => 'Promotions',
        'promotion_usage_releases' => 'Promotions',
        'promotion_usage_reservations' => 'Promotions',
        'provisioning_financial_invalidations' => 'Provisioning',
        'provisioning_operation_histories' => 'Provisioning',
        'provisioning_operations' => 'Provisioning',
        'provisioning_remote_effect_events' => 'Provisioning',
        'purchase_refunds' => 'Payments',
        'purchase_settlements' => 'Payments',
        'purchase_wallet_reservations' => 'Payments',
        'quotes' => 'Orders',
        'referral_attribution_events' => 'Promotions',
        'referral_identities' => 'Promotions',
        'referral_relationships' => 'Promotions',
        'referral_reward_accruals' => 'Promotions',
        'referral_reward_lifecycle_events' => 'Promotions',
        'referral_rewards' => 'Promotions',
        'refund_allocations' => 'Wallet',
        'refunds' => 'Wallet',
        'role_permissions' => 'AccessControl',
        'roles' => 'AccessControl',
        'sales_server_histories' => 'Panels',
        'sales_servers' => 'Panels',
        'scheduled_task_runs' => 'Operations',
        'sensitive_action_approvals' => 'AccessControl',
        'service_auto_renew_attempt_events' => 'Provisioning',
        'service_auto_renew_attempts' => 'Provisioning',
        'service_auto_renew_configuration_histories' => 'Provisioning',
        'service_auto_renew_configurations' => 'Provisioning',
        'service_auto_renew_notification_intents' => 'Provisioning',
        'service_batch_grant_items' => 'Provisioning',
        'service_batch_grants' => 'Provisioning',
        'service_delivery_attempts' => 'Provisioning',
        'service_imports' => 'Provisioning',
        'service_initial_delivery_fences' => 'Provisioning',
        'service_notification_delivery_bindings' => 'Provisioning',
        'service_notification_events' => 'Provisioning',
        'service_notification_scan_cursor' => 'Provisioning',
        'service_notification_states' => 'Provisioning',
        'service_operational_authority_capability' => 'Provisioning',
        'service_ownership_transfers' => 'Provisioning',
        'service_paid_mutation_authorities' => 'Provisioning',
        'service_reconciliation_cases' => 'Provisioning',
        'service_reconciliation_changes' => 'Provisioning',
        'service_subscriptions' => 'Provisioning',
        'service_sync_anomalies' => 'Provisioning',
        'service_sync_anomaly_events' => 'Provisioning',
        'service_sync_leases' => 'Provisioning',
        'service_sync_runs' => 'Provisioning',
        'service_sync_snapshots' => 'Provisioning',
        'service_username_registry' => 'Catalog',
        'sessions' => 'Framework',
        'sms_delivery_attempts' => 'Identity',
        'telegram_accounts' => 'Identity',
        'telegram_interaction_authority_capability' => 'Telegram',
        'telegram_interaction_callbacks' => 'Telegram',
        'telegram_interaction_sessions' => 'Telegram',
        'telegram_interaction_transitions' => 'Telegram',
        'telegram_interaction_update_bindings' => 'Telegram',
        'telegram_start_attributions' => 'Telegram',
        'trial_daily_capacity_counters' => 'Catalog',
        'trial_policies' => 'Catalog',
        'trial_policy_histories' => 'Catalog',
        'trial_policy_tags' => 'Catalog',
        'trial_policy_tiers' => 'Catalog',
        'trial_reservation_events' => 'Catalog',
        'trial_reservations' => 'Catalog',
        'usdt_amount_quotes' => 'Payments',
        'usdt_chain_verification_events' => 'Payments',
        'usdt_destination_wallet_versions' => 'Payments',
        'usdt_manual_rate_versions' => 'Payments',
        'usdt_manual_reviews' => 'Payments',
        'usdt_payment_authorities' => 'Payments',
        'usdt_reconciliation_findings' => 'Payments',
        'usdt_txid_submissions' => 'Payments',
        'usdt_verified_transfers' => 'Payments',
        'users' => 'Identity',
        'wallet_balance_snapshots' => 'Wallet',
        'wallet_correction_previews' => 'Wallet',
        'wallet_corrections' => 'Wallet',
        'wallet_holds' => 'Wallet',
        'wallet_top_up_settlements' => 'Payments',
        'wallet_transfers' => 'Wallet',
        'worker_heartbeats' => 'Operations',
        'zarinpal_payment_observations' => 'Payments',
        'zarinpal_payment_requests' => 'Payments',
        'zarinpal_payment_verifications' => 'Payments',
    ],

    // Exact temporary legacy seams only. Each entry is owned by #188 and CI rejects
    // stale/unused entries so the list shrinks as runtime boundaries are repaired.
    'persistence_exceptions' => [
        'app/Modules/Agents/Application/AgentApplicationService.php|users',
        'app/Modules/Customers/Application/CustomerAccountStateService.php|users',
        'app/Modules/Identity/Application/IdentityItemService.php|customer_profiles',
        'app/Modules/Identity/Application/OtpChallengeIssuer.php|customer_profiles',
        'app/Modules/Identity/Application/OtpChallengeVerifier.php|customer_profiles',
        'app/Modules/Identity/Application/TelegramContactVerifier.php|customer_profiles',
        'app/Modules/Provisioning/Application/InitialProvisioningQueueService.php|orders',
        'app/Modules/Provisioning/Application/InitialProvisioningQueueService.php|outbox_messages',
        'app/Modules/Provisioning/Application/ServiceDeliveryAttemptQueueService.php|outbox_messages',
        'app/Modules/Telegram/Application/TelegramIdentitySynchronizer.php|customer_profiles',
        'app/Modules/Telegram/Application/TelegramIdentitySynchronizer.php|telegram_accounts',
        'app/Modules/Telegram/Application/TelegramIdentitySynchronizer.php|users',
    ],
];
